name: Build EXE and Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag/Version name'
        required: true
        type: string

jobs:

  build:
    runs-on: windows-latest

    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install configparser
        pip install customtkinter
        pip install datetime
        pip install icalendar
        pip install pandas
        pip install tkcalendar
        pip install tk
        
        
    - name: Build executable
      run: |
        python build.py
        
    - name: Create executable folder
      run: |
        copy config.ini dist\mitgliederverwaltung\
        copy README.md dist\mitgliederverwaltung\
        copy Release_Notes.md dist\mitgliederverwaltung\
        copy example_file.xlsx dist\mitgliederverwaltung\
        cd dist
        dir
        Compress-Archive -Path ./mitgliederverwaltung -DestinationPath mitgliederverwaltung_${{ inputs.version }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mitgliederverwaltung_${{ inputs.version }}
        path: ./
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        draft: false
        prerelease: false
        
    - name: Upload zip file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist\mitgliederverwaltung_${{ inputs.version }}.zip
        asset_name: mitgliederverwaltung_${{ inputs.version }}.zip
        asset_content_type: application/zip
