name: Build EXE and Create Release

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest

    inputs:
      version:
          description: 'Tag/Version name'
          required: true
          type: string
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
        
    - name: Build executable
      run: |
        pyinstaller --onefile mitgliederverwaltung.py
        
    - name: Create executable folder
      run: |
        mkdir executable
        copy config.ini executable
        copy README.md executable
        copy dist\mitgliederverwaltung.exe executable\mitgliederverwaltung_${{ inputs.version }}.exe
        dir executable
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable-${{ inputs.version }}
        path: executable/
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./executable/mitgliederverwaltung_${{ inputs.version }}.exe
        asset_name: mitgliederverwaltung_${{ inputs.version }}.exe
        asset_content_type: application/vnd.microsoft.portable-executable